spring:
  application:
    name: marigold
  servelet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: dev
    include: oauth

server:
  servlet:
    session:
      timeout: 30m   # 30분 (JWT 사용 시 무시됨)

# JWT 설정
jwt:
  secret:
    defaultSecretKeyForDevelopmentOnlyChangeInProduction: JdmdwMCVtKkBDE2fav8dONZMGQcVvkPgyA36C4W9B8F # HS526
  access-token-validity-in-seconds: 3600  # 1시간
  refresh-token-validity-in-seconds: 86400 # 24시간